base_dir: ''
dataset_dir: 'datasets'  # 数据集保存的目录
source_dir: 'sources'  # 素材保存的目录

# bilibili
keywords_num: 10  # 做几个视频（1~10）
day_range: 3  # 获取几天内的数据
base_sleep_time: 1.2  # 每次请求之间的延迟（秒）
max_retries: 3  # 最大重试次数
concurrent_keywords: 3  # 并发获取关键词的数目

# Pexels API 配置   默认情况下，API 每小时限制 200 次请求，每月限制 20,000 次请求。
pexels_api_key: 你的api_key
pexels_base_url: https://api.pexels.com/videos/search
pexels_max_concurrent: 3 # 最大并发请求数量
pexels_sleep: 0.5  # 每次请求之间的延迟（秒）


# hunyuan API 配置
hunyuan_api_key: 你的api_key
hunyuan_base_url: https://api.hunyuan.cloud.tencent.com/v1
hunyuan_max_concurrent: 5 # 最大并发请求数量

# #creat videos #我电脑带不动异步并行
# max_create_workers: 1 #
# max_concurrent_create_videos: 1 # 最大并发创建视频的数目


# upload videos to bilibili
bili_cookie: 你的cookie
